# This is a basic workflow to help you get started with Actions
name: Deploy To Server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: src/Tools.UI/tools.ui/pnpm-lock.yaml
          
      - run: cd src/Tools.UI/tools.ui
      - run: pnpm install --frozen-lockfile
      - run:  pnpm run build

      # https://github.com/marketplace/actions/ssh-deploy
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "--delete"
          SOURCE: "src/Tools.UI/tools.ui/dist/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
